# Generated by Django 2.2.5 on 2020-01-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
