# Generated by Django 2.2.5 on 2020-01-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Product.Product')),
                ('offer', models.FloatField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
