# Generated by Django 2.2.5 on 2020-01-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('Offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=100)),
                ('count', models.CharField(max_length=255)),
                ('credit_card', models.CharField(max_length=20)),
                ('offer_at_the_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offer.Offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product')),
            ],
        ),
    ]
