# Generated by Django 2.2.5 on 2020-02-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0003_auto_20200222_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='offer_at_the_time',
            field=models.FloatField(null=True),
        ),
    ]
